(ns cadejo.instruments.alias.editor.alias-editor
  (:require [cadejo.ui.instruments.instrument-editor :as ied])
  (:require [cadejo.ui.instruments.subedit :as subedit])
  (:require [cadejo.ui.util.lnf :as lnf])
  (:require [cadejo.instruments.alias.editor.osc-editor :as osced])
  ;; (:require [cadejo.instruments.alias.editor.noise-editor :as noiseed])
  ;; (:require [cadejo.instruments.alias.editor.filter-editor :as filter])
  ;; (:require [cadejo.instruments.alias.editor.efx-editor :as efxed])
  ;; (:require [cadejo.instruments.alias.editor.mixer-editor :as mixer])
  ;; (:require [cadejo.instruments.alias.editor.env-editor :as enved])
  ;; (:require [cadejo.instruments.alias.editor.lfo-editor :as lfoed])
  ;; (:require [cadejo.instruments.alias.editor.stepper-editor :as steped])
  ;; (:require [cadejo.instruments.alias.editor.divider-editor :as dived])
  ;; (:require [cadejo.instruments.alias.editor.snh-editor :as snh])
  ;; (:require [cadejo.instruments.alias.editor.matrix-editor :as matrix])
  (:require [seesaw.core :as ss])
  )

(def sin-icon (lnf/read-icon :wave :sine))


(defn alias-editor [performance]
  (let [ied (ied/instrument-editor performance)
        osc (osced/osc-editor performance ied)
        ;; noise (noiseed/noise-editor performance ied)
        ;; f1 (filter/filter-editor 1 performance ied)
        ;; f2 (filter/filter-editor 2 performance ied)
        ;; efx (efxed/efx-editor performance ied)
        ;; mix (mixer/mixer performance ied)
        ;; env (enved/envelope-editor performance ied)
        ;; lfo (lfoed/lfo-editor performance ied)
        ;; pan-env-lfo (ss/scrollable (ss/vertical-panel 
        ;;                             :items [(.widget env :pan-main)
        ;;                                     (.widget lfo :pan-main)]))
        ;; env-lfo (subedit/subeditor-wrapper [env lfo] pan-env-lfo)
        ;; stepper (steped/step-counter-editor performance ied)
        ;; divider (dived/divider-editor performance ied)
        ;; snhed (snh/sample-and-hold performance ied)
        ;; mated (matrix/matrix-editor performance ied)
        ]
    (.add-sub-editor! ied "OSC" osc)
   
    ;; (.add-sub-editor! ied "Noise" noise)
    ;; (.add-sub-editor! ied "Filter 1" f1)
    ;; (.add-sub-editor! ied "Filter 2" f2)
    ;; (.add-sub-editor! ied "EFX" efx)
    ;; (.add-sub-editor! ied "Mixer" mix)
    ;; (.add-sub-editor! ied "Env/LFO" env-lfo)
    ;; (.add-sub-editor! ied "Step Counters" stepper)
    ;; (.add-sub-editor! ied "Clock Divider" divider)
    ;; (.add-sub-editor! ied "Sample & Hold" snhed)
    ;; (.add-sub-editor! ied "Matrix" mated)
    ied))
