(ns cadejo.instruments.algo.algo-constants)

;; (def dbar-cell-width 25)
;; (def dbar-cell-height 35)
;; (def dbar-style :matrix)
(def slider-length 150)
(def slider-spacing 50)
(def minor-tick-length 12)
(def major-tick-length 16)
(def min-feedback 0.0)
(def max-feedback 4.0)
(def max-feedback-mod 3.0)
(def min-feedback-mod (* -1 max-feedback-mod))
(def min-hp-freq 1)   ;; interop high-pass filter
(def max-hp-freq 50)
(def min-lp-freq 1000) ;; output low-pass filter
(def max-lp-freq 10000)
(def max-echo-delay 1.0)
(def min-echo-fb -0.95)
(def max-echo-fb  0.95)
(def min-amp-db -48)
(def max-amp-db 0)
(def max-vibrato-sensitivity 0.10)
(def max-vibrato-delay 4.0)
(def max-port-time 0.333)
(def default-envelope-view [[-0.2 -0.1][8.0 1.1]])
(def max-pitch-modulation 0.1)
(def min-pitch-modulation (* -1 max-pitch-modulation))
